[package]
name = "apod"
version = "0.1.0"
authors = ["Guido Knips <guido.knips@posteo.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.11.2", features = ["json", "blocking"] }
serde = { version = "^1.0.123", features = ["derive"] }
serde_json = "^1.0.59"
chrono = { version = "^0.4.19", features = ["serde"] }
bytes = "^1.0.1"
